# Generated by Django 5.1.4 on 2024-12-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('code', models.SmallIntegerField()),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Otc',
        ),
    ]
