# Generated by Django 5.1.4 on 2025-03-08 20:49

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostan', models.CharField(max_length=50)),
                ('shahrestan', models.CharField(max_length=70)),
                ('full_adress', models.TextField()),
                ('codeposty', models.PositiveIntegerField()),
                ('phone_number', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('code_rahgiry', models.PositiveBigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='adress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
