# Generated by Django 5.1.4 on 2025-03-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='codeposty',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='adress',
            name='phone_number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
