# Generated by Django 5.1.4 on 2025-03-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_adress_codeposty_alter_adress_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='code_rahgiry',
        ),
    ]
