# Generated by Django 5.1.4 on 2025-03-24 11:46

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_adress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='useradress', to=settings.AUTH_USER_MODEL),
        ),
    ]
