# Generated by Django 5.1.4 on 2025-03-25 12:23

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
