# Generated by Django 5.1.4 on 2025-04-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subblogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
