# Generated by Django 5.1.4 on 2025-04-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subblogs',
            name='title',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
