# Generated by Django 5.1.4 on 2025-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_subblogs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255),
        ),
    ]
