# Generated by Django 5.1.4 on 2025-04-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogs_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='sender',
            field=models.CharField(default='faeze', max_length=100),
        ),
    ]
