# Generated by Django 5.1.4 on 2025-01-24 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_category_category_is_sub_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='sub_category',
        ),
    ]
