# Generated by Django 5.1.4 on 2025-03-10 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5, 'your score must be less than 5 star'), django.core.validators.MinValueValidator(1, 'your score must be more than 1 star')]),
        ),
    ]
