# Generated by Django 5.1.4 on 2025-03-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_comment_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
