# Generated by Django 5.1.4 on 2025-03-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='user_comment',
        ),
    ]
