# Generated by Django 5.1.4 on 2025-03-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_comment_comment_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_comment',
            field=models.CharField(max_length=9999),
        ),
    ]
