# Generated by Django 5.1.4 on 2025-03-17 11:03

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_comment_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=colorfield.fields.ColorField(default='black', image_field=None, max_length=25, samples=None),
        ),
    ]
