# Generated by Django 5.1.4 on 2025-03-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_products_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color_name',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
    ]
