# Generated by Django 5.1.4 on 2025-03-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_products_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_comment',
            field=models.TextField(),
        ),
    ]
