# Generated by Django 5.1.4 on 2025-05-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_comment_dislikes_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dislikes',
            new_name='dislike',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='like',
        ),
    ]
