# Generated by Django 5.1.4 on 2025-05-24 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_products_color_remove_products_color_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolors',
            name='color',
        ),
        migrations.AddField(
            model_name='productcolors',
            name='color',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='home.products'),
        ),
    ]
