# Generated by Django 5.1.4 on 2025-05-24 10:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_productcolors_color_productcolors_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolors',
            name='color_piker',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
