# Generated by Django 5.1.4 on 2025-05-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_productcolors_color_piker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcolors',
            old_name='color',
            new_name='product',
        ),
    ]
