# Generated by Django 5.1.4 on 2025-05-25 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_comment_score_commentscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='CommentScore',
        ),
    ]
