# Generated by Django 5.1.4 on 2025-05-26 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_comment_score_delete_commentscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5, 'امتیاز شما باید بین 1 تا 5 باشد'), django.core.validators.MinValueValidator(1, 'امتیاز شما باید بین 1 تا 5 باشد')]),
        ),
    ]
