# Generated by Django 5.1.4 on 2025-05-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_comment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolors',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
