# Generated by Django 5.2.4 on 2025-07-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_promobanner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promobanner',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
