# Generated by Django 5.2.4 on 2025-07-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_promobanner_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoBanner',
        ),
    ]
